#!/bin/bash
# NEXTFLOW TASK: BQSR
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a ALL_CHILD
    while read P PP;do
        ALL_CHILD[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    walk() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${ALL_CHILD[$1]:=}; do walk $i; done
    }

    walk $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

on_exit() {
  exit_status=${ret:=$?}
  printf $exit_status > /projects/bioinformatics/PrakruthiWork/Genomics_MGC_VariantCalling_Nextflow/work/a5/7002660e267f172b6b97fd68139750/work/b4/5718c59bca06f4c6498bcd70397d71/.exitcode
  set +u
  [[ "$tee1" ]] && kill $tee1 2>/dev/null
  [[ "$tee2" ]] && kill $tee2 2>/dev/null
  [[ "$ctmp" ]] && rm -rf $ctmp || true
  exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

trap on_exit EXIT
trap on_term TERM INT USR1 USR2

NXF_SCRATCH=''
[[ $NXF_DEBUG > 0 ]] && nxf_env
touch /projects/bioinformatics/PrakruthiWork/Genomics_MGC_VariantCalling_Nextflow/work/a5/7002660e267f172b6b97fd68139750/work/b4/5718c59bca06f4c6498bcd70397d71/.command.begin
[[ $NXF_SCRATCH ]] && echo "nxf-scratch-dir $HOSTNAME:$NXF_SCRATCH" && cd $NXF_SCRATCH
# stage input files
rm -f Homo_sapiens_assembly38_chr20_21_22.fasta
rm -f Homo_sapiens_assembly38_chr20_21_22.fasta.fai
rm -f NextflowWorkflowPB.aligned.sorted.deduped.realigned.bam
rm -f NextflowWorkflowPB.aligned.sorted.deduped.realigned.bam.bai
rm -f realign_env.txt
ln -s /projects/bioinformatics/DataPacks/human/Hg38_chr20_21_22_simulated_data_Jan_2018/reference_and_index/Homo_sapiens_assembly38_chr20_21_22.fasta Homo_sapiens_assembly38_chr20_21_22.fasta
ln -s /projects/bioinformatics/DataPacks/human/Hg38_chr20_21_22_simulated_data_Jan_2018/reference_and_index/Homo_sapiens_assembly38_chr20_21_22.fasta.fai Homo_sapiens_assembly38_chr20_21_22.fasta.fai
ln -s /projects/bioinformatics/PrakruthiWork/NextflowRuns/NextflowWorkflowPB.aligned.sorted.deduped.realigned.bam NextflowWorkflowPB.aligned.sorted.deduped.realigned.bam
ln -s /projects/bioinformatics/PrakruthiWork/NextflowRuns/NextflowWorkflowPB.aligned.sorted.deduped.realigned.bam.bai NextflowWorkflowPB.aligned.sorted.deduped.realigned.bam.bai
ln -s /projects/bioinformatics/PrakruthiWork/env_files/realign_env.txt realign_env.txt

set +e
ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
cout=$ctmp/.command.out; mkfifo $cout
cerr=$ctmp/.command.err; mkfifo $cerr
tee .command.out < $cout &
tee1=$!
tee .command.err < $cerr >&2 &
tee2=$!
(
/bin/bash -ue /projects/bioinformatics/PrakruthiWork/Genomics_MGC_VariantCalling_Nextflow/work/a5/7002660e267f172b6b97fd68139750/work/b4/5718c59bca06f4c6498bcd70397d71/.command.sh
) >$cout 2>$cerr &
pid=$!
wait $pid || ret=$?
wait $tee1 $tee2
